/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { MenuItem, Review } from './types';

export const CATEGORIES = [
  { id: 'all', name: 'All Dishes', hindiName: 'सब कुछ' },
  { id: 'thali', name: 'Maa Ki Thali (Meals)', hindiName: 'माँ की थाली' },
  { id: 'snacks', name: 'Snacks & Parathas', hindiName: 'नाश्ता और पराठे' },
  { id: 'sweets', name: 'Maa Ke Hath Ki Mithai', hindiName: 'घर की मिठाई' },
  { id: 'beverages', name: 'Kulhad Drinks & Chai', hindiName: 'कुल्हड़ पेय और चाय' },
] as const;

export const INITIAL_MENU_ITEMS: MenuItem[] = [
  {
    id: 'thali-1',
    name: 'Ghar Ki Special Thali',
    hindiName: 'घर की स्पेशल थाली',
    description: 'A complete rich home meal: Paneer Sabzi, Slow-cooked Dal Fry, Dry Seasonal Veg, Creamy Bundi Raita, Jeera Basmati Rice, 4 fresh Butter Phulkas, sweet Kheer, Salad, and homemade Lemon Achar.',
    price: 180,
    category: 'thali',
    image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?q=80&w=800',
    isVeg: true,
    isSpicy: 'medium',
    isPopular: true,
    rating: 4.9,
  },
  {
    id: 'thali-2',
    name: 'Sada Ghar Ki Thali',
    hindiName: 'सादा घर की थाली',
    description: 'Perfect daily comfort food: Yellow Dal Tadka, Seasonal dry sabzi (Alloo Gobhi/Bhindi), 4 soft whole-wheat Phulkas, steamed Basmati rice, and fresh farm salad.',
    price: 120,
    category: 'thali',
    image: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?q=80&w=800',
    isVeg: true,
    isSpicy: 'low',
    rating: 4.7,
  },
  {
    id: 'thali-3',
    name: 'Special Kadhi Chawal Thali',
    hindiName: 'कढ़ी चावल थाली',
    description: 'Authentic Gohana style tangy buttermilk kadhi infused with onion pakoras and whole spices, served with a big portion of soft Basmati rice, roasted papad, and mint chutney.',
    price: 130,
    category: 'thali',
    image: 'https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?q=80&w=800',
    isVeg: true,
    isSpicy: 'medium',
    rating: 4.8,
  },
  {
    id: 'snacks-1',
    name: 'Gohana Special Aloo Paratha Combo',
    hindiName: 'आलू पराठा (मक्खन के साथ)',
    description: 'Two large golden-griddled whole wheat parathas stuffed with a spiced potato mash. Served with fresh homemade white butter (Safed Makhan), thick curd, and green chilli pickle.',
    price: 90,
    category: 'snacks',
    image: 'https://images.unsplash.com/photo-1626132647523-66f5bf380027?q=80&w=800',
    isVeg: true,
    isSpicy: 'medium',
    isPopular: true,
    rating: 4.9,
  },
  {
    id: 'snacks-2',
    name: 'Desi Ghee Kachori Sabzi (3 Pcs)',
    hindiName: 'कचौड़ी सब्ज़ी',
    description: 'Three crispy, flaky kachoris stuffed with spiced lentils, served with spicy & tangy mathura-style potato curry (aloo rassa) and sweet-sour tamarind chutney.',
    price: 80,
    category: 'snacks',
    image: 'https://images.unsplash.com/photo-1601050690597-df056fb4ce78?q=80&w=800',
    isVeg: true,
    isSpicy: 'high',
    rating: 4.7,
  },
  {
    id: 'snacks-3',
    name: 'Crispy Paneer Pakora Basket',
    hindiName: 'पनीर पकोड़ा बास्केट',
    description: 'Gram flour-coated, mint-chutney-layered fresh paneer blocks deep-fried till airy & golden. Garnished with home masala and served with green chutney & ketchup.',
    price: 110,
    category: 'snacks',
    image: 'https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?q=80&w=800',
    isVeg: true,
    isSpicy: 'medium',
    rating: 4.6,
  },
  {
    id: 'sweets-1',
    name: 'Gohana Famous Desi Ghee Jalebi (250g)',
    hindiName: 'गोहाना की प्रसिद्ध जलेबी',
    description: 'The legendary giant, thick-loop jalebi made slow in pure Desi Ghee to keep it crispy outside and filled with luscious warm saffron syrup inside.',
    price: 120,
    category: 'sweets',
    image: 'https://images.unsplash.com/photo-1605197584547-c93ef1a9c5bc?q=80&w=800',
    isVeg: true,
    isSpicy: 'low',
    isPopular: true,
    rating: 5.0,
  },
  {
    id: 'sweets-2',
    name: 'Desi Ghee Gulab Jamun with Rabri Bowl',
    hindiName: 'गुलाब जामुन और रबड़ी',
    description: 'Two soft, warm Gulab Jamuns made in pure Desi Ghee, dipped in fragrant saffron-infused sugar syrup, served on a rich bed of cold, slow-simmered milk Rabri.',
    price: 150,
    category: 'sweets',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?q=80&w=800',
    isVeg: true,
    isSpicy: 'low',
    rating: 4.9,
  },
  {
    id: 'sweets-3',
    name: 'Moong Dal Halwa',
    hindiName: 'मूंग दाल हलवा',
    description: 'Rich, aromatic pudding crafted from yellow lentils roasted for hours in pure Desi Ghee, finished with condensed milk, cardamom, saffron, and almonds.',
    price: 130,
    category: 'sweets',
    image: 'https://images.unsplash.com/photo-1601303589851-9a74486663b6?q=80&w=800',
    isVeg: true,
    isSpicy: 'low',
    rating: 4.8,
  },
  {
    id: 'bev-1',
    name: 'Maa Ke Hath Wali Adrak Chai (Kulhad)',
    hindiName: 'माँ के हाथ की अदरक चाय',
    description: 'Freshly brewed milk tea simmered with generous amounts of crushed ginger, green cardamom, and custom spices. Served piping hot in an earthy clay Kulhad.',
    price: 30,
    category: 'beverages',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?q=80&w=800',
    isVeg: true,
    isSpicy: 'low',
    isPopular: true,
    rating: 4.9,
  },
  {
    id: 'bev-2',
    name: 'Kulhad Kesar Badam Lassi',
    hindiName: 'केसर बादाम लस्सी',
    description: 'Rich, extra-thick hand-churned yogurt beverage sweetened with organic sugar, infused with Kashmiri saffron, and loaded with crushed almonds & pistachios.',
    price: 70,
    category: 'beverages',
    image: 'https://images.unsplash.com/photo-1571115177098-24ec4209e548?q=80&w=800',
    isVeg: true,
    isSpicy: 'low',
    rating: 4.8,
  },
  {
    id: 'bev-3',
    name: 'Masala Kulhad Chaach',
    hindiName: 'मसाला छाछ',
    description: 'Refreshing, spiced buttermilk prepared with fresh yogurt, roasted ground cumin, crushed mint, green coriander, ginger juice, and pink salt.',
    price: 40,
    category: 'beverages',
    image: 'https://images.unsplash.com/photo-1541658016709-82535e94bc69?q=80&w=800',
    isVeg: true,
    isSpicy: 'low',
    rating: 4.7,
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    author: 'Deepak Malik',
    rating: 5,
    comment: 'The Desi Ghee Jalebi is absolutely heavenly! It is just like the legendary Gohana flavor I grew up with. Their special thali feels so lightweight, clean, and nutritious.',
    date: 'July 2, 2026',
    dishName: 'Gohana Famous Desi Ghee Jalebi (250g)',
  },
  {
    id: 'rev-2',
    author: 'Priyanka Sharma',
    rating: 5,
    comment: 'Amazing hospitality! Felt like I was sitting in my mother’s kitchen. The butter on the Aloo Paratha is genuine home-made white butter. Must visit with family!',
    date: 'June 28, 2026',
    dishName: 'Gohana Special Aloo Paratha Combo',
  },
  {
    id: 'rev-3',
    author: 'Sandeep Hooda',
    rating: 5,
    comment: 'Kadhi Chawal thali tastes incredible. Perfectly sour, spicy, and non-greasy. Best place in Gohana for real ghar jaisa khana.',
    date: 'June 22, 2026',
    dishName: 'Special Kadhi Chawal Thali',
  },
];
